#!/bin/bash

cd scintilla/win32
mv ./makefile ./makefile.---
mv ./makefile-mingw-mac ./makefile
make
mv ./makefile ./makefile-mingw-mac
mv ./makefile.--- ./makefile

cd ../../scite/win32
mv ./makefile ./makefile.---
mv ./makefile-mingw-mac ./makefile
make
mv ./makefile ./makefile-mingw-mac
mv ./makefile.--- ./makefile
cd ../..
cp ./scite/bin/SciTE.exe ./Release/SciTE.exe
cp ./scite/bin/SciTE.exe ./Sc1IDE/Sc1.exe

cd ./iconlib/ico
./build-on-mac

